import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

export const openSans = Open_Sans({ 
  subsets: ['latin'],
  weight: ['300','400','500','600','700'],
  variable: '--font-open-sans'
})

export const metadata: Metadata = {
  title: 'Dobujack Catalogue',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
